server:
  port: 8080
  servlet:
    session:
      timeout: 3600s #seconds
      cookie:
        name: JSESSIONID
        domain: kevin.com
        http-only: true
        path: /
  connection-timeout: 5000 #ms
  
spring:
  application:
    name: sessionSharing
  datasource:
        name: test
        url: jdbc:mysql://192.168.1.169:3306/gps_tuning?useUnicode=true&amp;characterEncoding=UTF-8
        username: ifm
        password: ifm
        driver-class-name: com.mysql.jdbc.Driver
        hikari:
            connectionTimeout: 60000 #ms
            validationTimeout: 5000 #ms
            idleTimeout: 600000 #ms
            maxLifetime: 1800000 #ms
            minimumIdle: 10
            maximumPoolSize: 100
            connectionInitSql: select 1
            autoCommit: true
  redis:
        host: 192.168.1.204
        password: 
        port: 6379
        timeout: 10000 #ms
        jedis:
         pool:
          max-active: 100
          max-idle: 10
          min-idle: 1
          max-wait: 30000 #ms
  session:
    store-type: redis
    timeout: 3600s #seconds
    redis:
      flush-mode: immediate
      namespace: mySessionNamespace
  